apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "post.fullname" . }}
  labels:
    {{- include "post.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "post.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "post.selectorLabels" . | nindent 8 }}
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::520795059397:role/kiam_agent_ecr
    spec:
      imagePullSecrets:
        - name: awsecr-cred
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.POSTPORT }}
              protocol: TCP
              name: http
          env:
            - name: "POSTPORT"
              value: "{{ .Values.POSTPORT }}"
            - name: "BACKPORT"
              value: "{{ .Values.BACKPORT }}"
            - name: "BACKADDR"
              value: "{{ .Release.Name }}-{{ .Values.BACKADDR }}"
