apiVersion: v2
name: front
description: Flask web application
type: application
version: 0.1.0
appVersion: latest

dependencies:
  - name: prometheus
    version: "11.1.*"
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: grafana
    version: "5.0.*"
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: registry-creds
    version: "1.1.*"
    repository: https://kir4h.github.io/charts/
