- job_name:
  scrape_interval: 10s
  scrape_timeout: 15s
  #evaluation_interval: 30s
  metrics_path: /metrics
  kubernetes_sd_configs:
    - role: pod
  relabel_configs:
    - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_app_kubernetes_io_name]
      action: keep
      regex: default;
    - source_labels: [__meta_kubernetes_namespace]
      target_labels: namespace
    - source_labels: [__meta_kubernetes_pod]
      target_labels: pod
    - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
      target_labels: application