- job_name: demo-scrape-metrics
  scrape_interval: 20s
  scrape_timeout: 15s
  #evaluation_interval: 30s
  metrics_path: /metrics
  honor_labels: true
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_app_kubernetes_io_name, __meta_kubernetes_pod_container_port_name]
    action: keep
    regex: default;[a-z]{3,5};http
  - source_labels: [__meta_kubernetes_namespace]
    target_label: namespace
  - source_labels: [__meta_kubernetes_pod]
    target_label: pod
  - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
    target_label: application
