image:
  repository: 074368059797.dkr.ecr.eu-central-1.amazonaws.com/front
  tag: latest
  imagePullSecrets: awsecr-cred

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

URL_GET: get-srv:8081
URL_POST: post-srv:8082/a

global:
  kiam_server: arn:aws:iam::520795059397:role/kiam_server
  kiam_agent_ecr: arn:aws:iam::520795059397:role/kiam_agent_ecr
  kiam_agent_dynamodb: arn:aws:iam::520795059397:role/kiam_agent_dynamodb
  kiam_sha_version: 6e07571932910d71a8d99a7b4dd0325e09baf9b4

##### PROMETHEUS #####
prometheus:
  alertmanager:
    enabled: false
    persistentVolume:
      enabled: false

  server:
    global:
      scrape_interval: 30s
      scrape_timeout: 30s
      evaluation_interval: 1m
    persistentVolume:
      enabled: false

  pushgateway:
    enabled: false
    persistentVolume:
      enabled: false

  extraScrapeConfigs:

##### Grafana #####
grafana:

    persistence:
        enabled: false

    adminUser: admin
    adminPassdword:

    datasources:
        datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: "http://{{ .Release.Name }}-prometheus-server"
              access: proxy
              isDefault: true

    dashboardProviders:
        dashboardproviders.yaml:
            apiVersion: 1
            providers:
            - name: 'default'
              orgId: 1
              folder: ''
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
      
    dashboards:
      default:
        Demo-Dashboard:
          json:

