replicaCount: 1

image:
  repository: 074368059797.dkr.ecr.eu-central-1.amazonaws.com/front
  tag: latest
  imagePullSecrets: awsecr-cred

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

URL_GET: get-srv:8081
URL_POST: post-srv:8082/a

##### PROMETHEUS #####
prometheus:
  alertmanager:
        enabled: true
        persistentVolume:
            enabled: false

  server:
    global:
        scrape_interval: 30s
        scrape_timeout: 30s
        evaluation_interval: 1m


##### Grafana #####
grafana:

    persistence:
        ebabled: false

    adminUser: admin
    adminPassdword:

    datasources:
        datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: "http://{{ .Release.Name }}-prometheus-server"
              access: proxy
              isDefault: true

    dashboardProviders:
        dashboardproviders.yaml:
            apiVersion: 1
            providers:
            - name: 'default'
              orgId: 1
              folder: ''
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
