tags:
  monitoring: false
  iam: false

image:
  repository: 074368059797.dkr.ecr.eu-central-1.amazonaws.com/front
  tag: latest
  imagePullSecrets: awsecr-cred

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

URL_GET: get-srv:8081
URL_POST: post-srv:8082/a

registry-creds:
  enabled: false

global:
  kiam_server: arn:aws:iam::520795059397:role/kiam_server
  kiam_agent_ecr: arn:aws:iam::520795059397:role/kiam_agent_ecr
  kiam_agent_dynamodb: arn:aws:iam::520795059397:role/kiam_agent_dynamodb

##### PROMETHEUS #####
prometheus:

  alertmanager:
    enabled: false
    persistentVolume:
      enabled: false

  server:
    global:
      scrape_interval: 30s
      scrape_timeout: 30s
      evaluation_interval: 1m
    persistentVolume:
      enabled: false

  pushgateway:
    enabled: false
    persistentVolume:
      enabled: false

  extraScrapeConfigs:

##### Grafana #####
grafana:

  #Values.namespaceOverride:

  persistence:
      enabled: false

  adminUser: admin
  adminPassdword:

  datasources:
      datasources.yaml:
          apiVersion: 1
          datasources:
          - name: Prometheus
            type: prometheus
            url: "http://{{ .Release.Name }}-prometheus-server"
            access: proxy
            isDefault: true

  dashboardProviders:
      dashboardproviders.yaml:
          apiVersion: 1
          providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
    
  dashboards:
    default:
      Demo-Dashboard:
        json:

# ##### KIAM #####
kiam:

  imagePullSecrets: awsecr-cred

  agent:
    name: kiam-agent
    host:
      iptables: true
      # do not remove iptables forwarding rules when kiam-agent terminates
      # needed for RollingUpdate strategy and for security reeasons
      # see https://github.com/uswitch/kiam/issues/202 and https://github.com/uswitch/kiam/pull/253
      iptablesRemoveOnShutdown: false
      port: 8181
      interface: cbr0

    updateStrategy: RollingUpdate

    nodeSelector:
      kubernetes.io/role: node

    tlsSecret: kiam-ca-key-pair


  server:

    name: kiam-server

    updateStrategy: RollingUpdate

    nodeSelector:
      kubernetes.io/role: master

    tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule

    probes:
      serverAddress: localhost

    tlsSecret: kiam-ca-key-pair

    ## Base ARN for IAM roles
    ## If not specified use EC2 metadata service to detect ARN prefix
    ##
    roleBaseArn: null
    ## IAM role for the server to assume
    ##
    assumeRoleArn: kiam_server

##### cert-manager #####
cert-manager:
  installCRDs: true