apiVersion: v1
kind: Service
metadata:
  name: {{ include "back.fullname" . }}-srv
  labels:
    {{- include "back.labels" . | nindent 4 }}
spec:
  type: {{ .Values.typePort }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.targetPort }}
  selector:
    {{- include "front.selectorLabels" . | nindent 4 }}
